glim-token: ENC[AES256_GCM,data:Hxbu5PMrtW1VZQeHXYiI9+r2VNNgXze1S22mtInCfkJhdQ83UdAzdBlS+usdkR8YUtzzv3bGVJm+,iv:r45IsTvaAOYe9sns2JqhhBgr2j3GQ7DxRegvqzSY1CY=,tag:1qmEaTN0YYQ0EOYxRyD69w==,type:str]
sops:
    age:
        - recipient: age1gnmqucyk3vgkk4zu9rwkywnn5s6u6qk5z28akreujs0hhy4aggaszpxcvc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWEZHb29KU3RqT3FsUWpP
            aGRJZHJWWXpydjE3dmZGMTcyU0ZWRm93NEZZCjcyQlh4bFFBK0lvU2dwd1pqVVV2
            eG5XZDRCVU02ZEZFeEpMaFdiNXJyRXcKLS0tIE5TWXc4RThta3A2MXBGZVJaVENs
            aE1ZQ1I1dmlzU3BDUVovVDAwRDlnam8KlxLEaUcdZ+1jM9ihEsMRvoAwbdUJXlMW
            KB8ro0wL4ulV6QtVFZe7vI8nb9vLBi13vcjQXJhTm7lsJ/wBrn4Dqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T17:30:30Z"
    mac: ENC[AES256_GCM,data:ad1A9CCte0+ZB9ActyINr2451Do1TbdpGBppAHvjWPQ+yyXlWOhi8MGBcIRlKEPbUoF6OzRxGROg/4QmwWGIUZDomFchyHk1bslLCnS/9e9+UlOFw+gdVBwDCqpb+phw8p6qLCMowtr8bQiw7FfnTtlU/+Suu77jwwDpV8gObSA=,iv:tLlwMJq0/XR9UU1gEy+cfnAb3mzD9TGsA7PTy05Rd8g=,tag:H0GcwHMwEYwLf/esXASpxQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
