glim-token: ENC[AES256_GCM,data:Hxbu5PMrtW1VZQeHXYiI9+r2VNNgXze1S22mtInCfkJhdQ83UdAzdBlS+usdkR8YUtzzv3bGVJm+,iv:r45IsTvaAOYe9sns2JqhhBgr2j3GQ7DxRegvqzSY1CY=,tag:1qmEaTN0YYQ0EOYxRyD69w==,type:str]
browser-pinned: ENC[AES256_GCM,data:2r7zOc57JgCMvD8BCxKoeTeYImSfTPVXb93rn1NnWFT8JjJ/MrHgwEF2BCemF1nYg1wS08RuciqRzD+2HCKnLD/4DSFWXJzvCEdK9GlaNm5hXy/tQqEa1bgvgyGcKhhBTfOMtHQApre3EXFnuia9/mLFJTtF58xZhJHxS58PqqsFMJrSVgmjmaibklQx87a70O6Ou0jWGvmmspwT8zz5kTcYZ2MCrIRDiuNQF8aJ0yRLm0roWahCjmaFwGSWwzYy/A4tqQUDIQYogFbqNyIiAs+xiXTnTSYx+k8gwI119XuZ7EnAIcsCrGTwQ5rH+6eqX6bY/yoQ6jc9bbj7Y7iSEvrUkMlMY5LeDHaXBlSvKEMPT/jruWAqKcPNXnZ+z3Q=,iv:YyHrLieNB24ke279joT5w1zLM3zn4XTc70lAFpaRWf4=,tag:7LuYGgjxmaYMXjxitaqdpg==,type:str]
sops:
    age:
        - recipient: age1gnmqucyk3vgkk4zu9rwkywnn5s6u6qk5z28akreujs0hhy4aggaszpxcvc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWEZHb29KU3RqT3FsUWpP
            aGRJZHJWWXpydjE3dmZGMTcyU0ZWRm93NEZZCjcyQlh4bFFBK0lvU2dwd1pqVVV2
            eG5XZDRCVU02ZEZFeEpMaFdiNXJyRXcKLS0tIE5TWXc4RThta3A2MXBGZVJaVENs
            aE1ZQ1I1dmlzU3BDUVovVDAwRDlnam8KlxLEaUcdZ+1jM9ihEsMRvoAwbdUJXlMW
            KB8ro0wL4ulV6QtVFZe7vI8nb9vLBi13vcjQXJhTm7lsJ/wBrn4Dqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T02:30:03Z"
    mac: ENC[AES256_GCM,data:H95IZTfJJp7oc8QsT03GpE+/M6K3DngusJk5br8AT6/qH/733PH2H+flUXYonFIHNqs07fOPYZKb3uh5TKW+FngUqxUQULI9zdwp5RQpA395rHyVX2E1F6XZYr1g0dKRrReJYNvZLvCWFFOTKegKjOH3gVns+wDV2yhAcikMv40=,iv:Lm+SEG48fTJxzfsi30EVxZbenKKYOR4gJD5wNoIMHkc=,tag:YoPZD/4E4NZ0Lh7izYZWLA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
