# .sops.yaml
keys:
  - &primary age1gnmqucyk3vgkk4zu9rwkywnn5s6u6qk5z28akreujs0hhy4aggaszpxcvc
  - &dummy age1f5ee8vhhcsul3vgh0t6nvs860fv09ukuk0gs6trn24v9hx07vv0s2yjyyd

creation_rules:
  - path_regex: secrets/primary\.yaml$
    key_groups:
      - age:
          - *primary
  - path_regex: secrets/dummy\.yaml$
    key_groups:
      - age:
          - *dummy
