# .sops.yaml
keys:
  - &bazzite age1gnmqucyk3vgkk4zu9rwkywnn5s6u6qk5z28akreujs0hhy4aggaszpxcvc

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *bazzite
